n=input("Enter your name :")
c=int(input("Enter your class :"))
a=int(input("Enter your age :"))
print("Your name is",n,", you are in class",c,"and your age is",a)
print("\n")
print("Your name is :",n)
print("You are in class :",c)
print("You are",a,"years old")